
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Base64;
import java.util.Calendar;
import javax.swing.JOptionPane;
import java.sql.Timestamp;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author acv
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String currentSemester;
    private String author;
    private String projectDate;

    public MainFrame() {
        initComponents();
        checkData();
        rebuildSemesterComboBoxes();
        rebuildCourseComboBoxes();
        rebuildClassComboBoxes();
        rebuildStudentComboBoxes();
    }

    public void rebuildSemesterComboBoxes() {
        ArrayList<SemesterEntry> semesters = SemesterQueries.getSemesterList();
        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        if (semesters.size() > 0) {
            currentSemesterLabel.setText(semesters.get(0).toString());
            currentSemester = semesters.get(0).toString();
        } else {
            currentSemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
    }
    
    private void rebuildCourseComboBoxes() {
        ArrayList<String> courseCodes = CourseQueries.getAllCourseCodes();
        AddClass_CourseCode_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(courseCodes.toArray())); // Admin Add Class
    }

    private void rebuildClassComboBoxes() {
        ArrayList<String> classCodes = ClassQueries.getAllCourseCodes(currentSemester);
        // Student tab – Schedule Class
        ScheduleClass_SelectClass_ComboBox.setModel(
            new javax.swing.DefaultComboBoxModel(classCodes.toArray()));

        // Admin tab – Display Class List
        Admin_DisplayClassList_ChooseClass_ComboBox.setModel(
            new javax.swing.DefaultComboBoxModel(classCodes.toArray()));

        // Admin tab – Drop Class
        Admin_DropClass_ChoseClass_ComboBox.setModel(
            new javax.swing.DefaultComboBoxModel(classCodes.toArray()));
        
        Student_DropClass_ChooseClass_ComboBox.setModel(
        new javax.swing.DefaultComboBoxModel(classCodes.toArray()));
    }

    private void rebuildStudentComboBoxes() {
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();

        // Student tab
        ScheduleClass_SelectStudent_ComboBox.setModel(
            new javax.swing.DefaultComboBoxModel(students.toArray()));
        DisplaySchedule_SelectStudent_ComboBox.setModel(
            new javax.swing.DefaultComboBoxModel(students.toArray()));

        // Admin tab – Drop Student
        Admin_DropStudent_ChooseStudent_ComboBox.setModel(
            new javax.swing.DefaultComboBoxModel(students.toArray()));

        // (you’ll also use students again for Student-Drop-Class tab once you add it)
        Student_DropClass_ChooseStudent_ComboBox.setModel(
        new javax.swing.DefaultComboBoxModel(students.toArray()));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        Admin_Panel = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addSemesterTermTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addSemesterYearTextfield = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        addCourseCodeTextfield = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        addCourseDescriptionTextfield = new javax.swing.JTextField();
        addCourseSubmitButton = new javax.swing.JButton();
        addCourseStatusLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        AddClass_CourseCode_ComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        AddClass_Seats_Spinner = new javax.swing.JSpinner();
        AddClass_submit_Button = new javax.swing.JButton();
        AddClass_Display_textfield = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        StudentIDtextfield = new javax.swing.JTextField();
        AddStudent_FirstName_TextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        AddStudent_Display_TextField = new javax.swing.JLabel();
        AddStudent_LastName_TextField = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        Admin_DisplayClassList_ChooseClass_Label = new javax.swing.JLabel();
        Admin_DisplayClassList_ChooseClass_ComboBox = new javax.swing.JComboBox<>();
        Admin_DisplayClassList_Display_Button = new javax.swing.JButton();
        Admin_DisplayClassList_ScheduledStudents_Label = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Admin_DisplayClassList_ScheduledStudents_Table = new javax.swing.JTable();
        Admin_DisplayClassList_WaitlistStudents_Label = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Admin_DisplayClassList_WaitlistStudents_Table = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        Admin_DropStudent_ChooseStudent_Label = new javax.swing.JLabel();
        Admin_DropStudent_Submit_Button = new javax.swing.JButton();
        Admin_DropStudent_ChooseStudent_ComboBox = new javax.swing.JComboBox<>();
        jScrollPane9 = new javax.swing.JScrollPane();
        Admin_DropStudent_TextArea = new javax.swing.JTextArea();
        jPanel13 = new javax.swing.JPanel();
        Admin_DropClass_ChoseClass_Label = new javax.swing.JLabel();
        Admin_DropClass_ChoseClass_ComboBox = new javax.swing.JComboBox<>();
        Admin_DropClass_Submit_Button = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        Admin_DropClass_TextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        DisplayClasses_TextArea = new javax.swing.JTextArea();
        DisplayClasses_Display_Button = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        ScheduleClass_SelectClass_ComboBox = new javax.swing.JComboBox<>();
        ScheduleClass_Submit_Button = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        ScheduleClass_SelectStudent_ComboBox = new javax.swing.JComboBox<>();
        ScheduleClass_DisplayClassStudent_Label = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        DisplaySchedule_SelectStudent_ComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplaySchedule_TextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        DisplaySchedule_Table = new javax.swing.JTable();
        DisplaySchedule_Display_Button = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        Student_DropClass_ChooseStudent_Label = new javax.swing.JLabel();
        Student_DropClass_ChooseClass_Label = new javax.swing.JLabel();
        Student_DropClass_ChooseStudent_ComboBox = new javax.swing.JComboBox<>();
        Student_DropClass_ChooseClass_ComboBox = new javax.swing.JComboBox<>();
        Student_DropClass_Submit_Button = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        Student_DropClass_TextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");

        jLabel3.setText("Semester Term:");

        addSemesterTermTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                                                   ");

        jLabel4.setText("Semester Year:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(addSemesterSubmitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addSemesterTermTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(addSemesterYearTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTermTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(addSemesterYearTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addSemesterStatusLabel)
                    .addComponent(addSemesterSubmitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Add Semester", jPanel3);

        jLabel5.setText("Course Code:");

        addCourseCodeTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseCodeTextfieldActionPerformed(evt);
            }
        });

        jLabel6.setText("Course Description");

        addCourseSubmitButton.setText("Submit");
        addCourseSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseSubmitButtonActionPerformed(evt);
            }
        });

        addCourseStatusLabel.setText("                              ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseSubmitButton)
                            .addComponent(addCourseCodeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addCourseDescriptionTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addCourseCodeTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addCourseDescriptionTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addCourseSubmitButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCourseStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Add Course", jPanel4);

        jLabel11.setText("Course Code: ");

        AddClass_CourseCode_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel12.setText("Seats:");

        AddClass_submit_Button.setText("Submit");
        AddClass_submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClass_submit_ButtonActionPerformed(evt);
            }
        });

        AddClass_Display_textfield.setText("                          ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddClass_CourseCode_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(59, 59, 59)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddClass_submit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddClass_Seats_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(AddClass_Display_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AddClass_CourseCode_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(AddClass_Seats_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddClass_submit_Button)
                .addGap(18, 18, 18)
                .addComponent(AddClass_Display_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Add Class", jPanel6);

        jLabel7.setText("Student ID :");

        jLabel8.setText("First Name :");

        jLabel9.setText("Last Name :");

        StudentIDtextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDtextfieldActionPerformed(evt);
            }
        });

        AddStudent_FirstName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudent_FirstName_TextFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        AddStudent_Display_TextField.setText("                                             ");

        AddStudent_LastName_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudent_LastName_TextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddStudent_FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StudentIDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(AddStudent_LastName_TextField))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jButton1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddStudent_Display_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(StudentIDtextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AddStudent_FirstName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(AddStudent_LastName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(AddStudent_Display_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Add Student", jPanel7);

        Admin_DisplayClassList_ChooseClass_Label.setText("Choose Class :");

        Admin_DisplayClassList_ChooseClass_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Admin_DisplayClassList_Display_Button.setText("Display");
        Admin_DisplayClassList_Display_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_DisplayClassList_Display_ButtonActionPerformed(evt);
            }
        });

        Admin_DisplayClassList_ScheduledStudents_Label.setText("Scheduled Students in the Class:");

        Admin_DisplayClassList_ScheduledStudents_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "StudentID"
            }
        ));
        jScrollPane7.setViewportView(Admin_DisplayClassList_ScheduledStudents_Table);

        Admin_DisplayClassList_WaitlistStudents_Label.setText("Waitlisted Students in the Class in Waitlist Order :");

        Admin_DisplayClassList_WaitlistStudents_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Last Name", "First Name", "Student ID"
            }
        ));
        jScrollPane8.setViewportView(Admin_DisplayClassList_WaitlistStudents_Table);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admin_DisplayClassList_ScheduledStudents_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(Admin_DisplayClassList_ChooseClass_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Admin_DisplayClassList_ChooseClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(Admin_DisplayClassList_Display_Button))
                    .addComponent(jScrollPane7)
                    .addComponent(Admin_DisplayClassList_WaitlistStudents_Label)
                    .addComponent(jScrollPane8))
                .addContainerGap(647, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_DisplayClassList_ChooseClass_Label)
                    .addComponent(Admin_DisplayClassList_ChooseClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_DisplayClassList_Display_Button))
                .addGap(18, 18, 18)
                .addComponent(Admin_DisplayClassList_ScheduledStudents_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Admin_DisplayClassList_WaitlistStudents_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Display Class List", jPanel11);

        Admin_DropStudent_ChooseStudent_Label.setText("Choose Student :");

        Admin_DropStudent_Submit_Button.setText("Submit");
        Admin_DropStudent_Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_DropStudent_Submit_ButtonActionPerformed(evt);
            }
        });

        Admin_DropStudent_ChooseStudent_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Admin_DropStudent_TextArea.setColumns(20);
        Admin_DropStudent_TextArea.setRows(5);
        jScrollPane9.setViewportView(Admin_DropStudent_TextArea);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Admin_DropStudent_Submit_Button)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(Admin_DropStudent_ChooseStudent_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Admin_DropStudent_ChooseStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(561, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Admin_DropStudent_ChooseStudent_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(Admin_DropStudent_ChooseStudent_ComboBox)))
                .addGap(18, 18, 18)
                .addComponent(Admin_DropStudent_Submit_Button)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Drop Student", jPanel12);

        Admin_DropClass_ChoseClass_Label.setText("Chose Class :");

        Admin_DropClass_ChoseClass_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Admin_DropClass_Submit_Button.setText("Submit");
        Admin_DropClass_Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_DropClass_Submit_ButtonActionPerformed(evt);
            }
        });

        Admin_DropClass_TextArea.setColumns(20);
        Admin_DropClass_TextArea.setRows(5);
        jScrollPane6.setViewportView(Admin_DropClass_TextArea);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Admin_DropClass_ChoseClass_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Admin_DropClass_Submit_Button)
                            .addComponent(Admin_DropClass_ChoseClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_DropClass_ChoseClass_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Admin_DropClass_ChoseClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Admin_DropClass_Submit_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        Admin_Panel.addTab("Drop Class", jPanel13);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Admin_Panel)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Admin_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        DisplayClasses_TextArea.setColumns(20);
        DisplayClasses_TextArea.setRows(5);
        jScrollPane4.setViewportView(DisplayClasses_TextArea);

        DisplayClasses_Display_Button.setText("Display");
        DisplayClasses_Display_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayClasses_Display_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(DisplayClasses_Display_Button)))
                .addContainerGap(505, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(DisplayClasses_Display_Button)
                .addGap(23, 23, 23))
        );

        jTabbedPane3.addTab("Display Classes", jPanel5);

        jLabel14.setText("Select Class:");

        ScheduleClass_SelectClass_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ScheduleClass_Submit_Button.setText("Submit");
        ScheduleClass_Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleClass_Submit_ButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Select Student:");

        ScheduleClass_SelectStudent_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ScheduleClass_DisplayClassStudent_Label.setText("                               ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ScheduleClass_SelectStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScheduleClass_SelectClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ScheduleClass_Submit_Button)))
                    .addComponent(ScheduleClass_DisplayClassStudent_Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(646, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ScheduleClass_SelectClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ScheduleClass_SelectStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScheduleClass_Submit_Button)
                .addGap(18, 18, 18)
                .addComponent(ScheduleClass_DisplayClassStudent_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Schedule Class", jPanel8);

        jLabel17.setText("Select Student:");

        DisplaySchedule_SelectStudent_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        DisplaySchedule_TextArea.setColumns(20);
        DisplaySchedule_TextArea.setRows(5);
        jScrollPane1.setViewportView(DisplaySchedule_TextArea);

        DisplaySchedule_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Status"
            }
        ));
        jScrollPane5.setViewportView(DisplaySchedule_Table);

        DisplaySchedule_Display_Button.setText("Display");
        DisplaySchedule_Display_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplaySchedule_Display_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(DisplaySchedule_SelectStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(475, 475, 475)
                        .addComponent(DisplaySchedule_Display_Button)))
                .addContainerGap(511, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(DisplaySchedule_SelectStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(DisplaySchedule_Display_Button)
                .addGap(31, 31, 31))
        );

        jTabbedPane3.addTab("Display Schedule", jPanel9);

        Student_DropClass_ChooseStudent_Label.setText("Choose Student:");

        Student_DropClass_ChooseClass_Label.setText("Choose Class :");

        Student_DropClass_ChooseStudent_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Student_DropClass_ChooseStudent_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_DropClass_ChooseStudent_ComboBoxActionPerformed(evt);
            }
        });

        Student_DropClass_ChooseClass_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Student_DropClass_Submit_Button.setText("Submit");
        Student_DropClass_Submit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Student_DropClass_Submit_ButtonActionPerformed(evt);
            }
        });

        Student_DropClass_TextArea.setColumns(20);
        Student_DropClass_TextArea.setRows(5);
        jScrollPane10.setViewportView(Student_DropClass_TextArea);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Student_DropClass_ChooseClass_Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Student_DropClass_ChooseStudent_Label, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Student_DropClass_ChooseStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Student_DropClass_ChooseClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Student_DropClass_Submit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_DropClass_ChooseStudent_Label)
                    .addComponent(Student_DropClass_ChooseStudent_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Student_DropClass_ChooseClass_Label)
                    .addComponent(Student_DropClass_ChooseClass_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Student_DropClass_Submit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Drop Class", jPanel10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1060, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("Current Semester: ");

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeSemesterButton)
                .addGap(63, 63, 63)
                .addComponent(aboutButton)
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton)
                    .addComponent(aboutButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        // TODO add your handling code here:
        // display about information.
        JOptionPane.showMessageDialog(null, "Author: " + author + " Project Date: " + projectDate);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        currentSemesterLabel.setText(currentSemesterComboBox.getSelectedItem().toString());
        currentSemester = currentSemesterComboBox.getSelectedItem().toString();

    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    
    
    
    
    private void DisplaySchedule_Display_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplaySchedule_Display_ButtonActionPerformed
        StudentEntry student = (StudentEntry) DisplaySchedule_SelectStudent_ComboBox.getSelectedItem();
        if (student == null) {
            DisplaySchedule_TextArea.setText("Select a student first.");
            return;
        }

        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) DisplaySchedule_Table.getModel();
        model.setRowCount(0);

        ArrayList<ScheduleEntry> schedule =
            ScheduleQueries.getScheduleByStudent(currentSemester, student.getStudentID());

        StringBuilder sb = new StringBuilder();
        sb.append("Schedule for ").append(student.toString())
          .append(" - ").append(currentSemester).append("\n");

        for (ScheduleEntry se : schedule) {

            // Convert S/W to full text WITHOUT brackets
            String statusText = se.getStatus().equals("S") ? "Scheduled" : "Waitlisted";

            // Update table
            model.addRow(new Object[] { se.getCourseCode(), statusText });

            // Update top text area (no brackets)
            sb.append(se.getCourseCode()).append(" - ").append(statusText).append("\n");
        }

        DisplaySchedule_TextArea.setText(sb.toString());
    }//GEN-LAST:event_DisplaySchedule_Display_ButtonActionPerformed

    private void DisplayClasses_Display_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayClasses_Display_ButtonActionPerformed
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);

        // get all classes + descriptions for the current semester
        ArrayList<ClassDescription> list =
            MultiTableQueries.getAllClassDescriptions(currentSemester);

        // build the top text-area text
        StringBuilder sb = new StringBuilder();
        sb.append("Course Code\tDescription\tSeats\n");

        for (ClassDescription cd : list) {
            model.addRow(new Object[] {
                cd.getCourseCode(),
                cd.getDescription(),
                cd.getSeats()
            });

            sb.append(cd.getCourseCode()).append("\t")
              .append(cd.getDescription()).append("\t")
              .append(cd.getSeats()).append("\n");
        }

        DisplayClasses_TextArea.setText(sb.toString());
    }//GEN-LAST:event_DisplayClasses_Display_ButtonActionPerformed

    private void ScheduleClass_Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleClass_Submit_ButtonActionPerformed
        String courseCode = (String) ScheduleClass_SelectClass_ComboBox.getSelectedItem();
        StudentEntry student = (StudentEntry) ScheduleClass_SelectStudent_ComboBox.getSelectedItem();

        if (courseCode == null || student == null) {
            ScheduleClass_DisplayClassStudent_Label.setText("Please select both class and student.");
            return;
        }

        // how many can sit
        int seats = ClassQueries.getClassSeats(currentSemester, courseCode);
        // how many already scheduled (status = 'S')
        int scheduledCount = ScheduleQueries.getScheduledStudentCount(currentSemester, courseCode);

        String status;
        if (scheduledCount < seats) {
            status = "S";  // scheduled
        } else {
            status = "W";  // waitlisted
        }

        ScheduleEntry entry = new ScheduleEntry(
            currentSemester,
            courseCode,
            student.getStudentID(),
            status,
            new java.sql.Timestamp(System.currentTimeMillis())
        );

        ScheduleQueries.addScheduleEntry(entry);

        if (status.equals("S")) {
            ScheduleClass_DisplayClassStudent_Label.setText(
                student.toString() + " has been scheduled for the class");
        } else {
            ScheduleClass_DisplayClassStudent_Label.setText(
                student.toString() + " has been waitlisted for the class");
        }
    }//GEN-LAST:event_ScheduleClass_Submit_ButtonActionPerformed

    private void AddStudent_LastName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudent_LastName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStudent_LastName_TextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = StudentIDtextfield.getText().trim();
        String first = AddStudent_FirstName_TextField.getText().trim();
        String last = AddStudent_LastName_TextField.getText().trim();

        if (id.isEmpty() || first.isEmpty() || last.isEmpty()) {
            AddStudent_Display_TextField.setText("Please fill all fields.");
            return;
        }

        StudentEntry student = new StudentEntry(id, first, last);
        StudentQueries.addStudent(student);
        AddStudent_Display_TextField.setText(first + " " + last + " " + id + " added.");

        rebuildStudentComboBoxes();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AddStudent_FirstName_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudent_FirstName_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddStudent_FirstName_TextFieldActionPerformed

    private void StudentIDtextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDtextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDtextfieldActionPerformed

    private void AddClass_submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClass_submit_ButtonActionPerformed
        String courseCode = (String) AddClass_CourseCode_ComboBox.getSelectedItem();
        int seats = (Integer) AddClass_Seats_Spinner.getValue();

        if (courseCode == null) {
            AddClass_Display_textfield.setText("No course selected.");
            return;
        }

        // Create a new class offering for the current semester
        ClassEntry cls = new ClassEntry(currentSemester, courseCode, seats);
        ClassQueries.addClass(cls);

        AddClass_Display_textfield.setText(
            "Class " + courseCode + " added for " + currentSemester + "."
        );

        // update the Student tab class combo
        rebuildClassComboBoxes();
    }//GEN-LAST:event_AddClass_submit_ButtonActionPerformed

    private void addCourseSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseSubmitButtonActionPerformed
        String code = addCourseCodeTextfield.getText().trim();
        String desc = addCourseDescriptionTextfield.getText().trim();

        if (code.isEmpty() || desc.isEmpty()) {
            addCourseStatusLabel.setText("Please enter both course code and description.");
            return;
        }

        CourseEntry course = new CourseEntry(code, desc);
        CourseQueries.addCourse(course);
        addCourseStatusLabel.setText("Course " + code + " has been added.");

        // refresh course list for Add Class
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_addCourseSubmitButtonActionPerformed

    private void addCourseCodeTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseCodeTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCourseCodeTextfieldActionPerformed

    private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
        String semesterTerm = addSemesterTermTextfield.getText();
        String semesterYear = addSemesterYearTextfield.getText();
        SemesterEntry semester = new SemesterEntry(semesterTerm, semesterYear);
        SemesterQueries.addSemester(semester);
        addSemesterStatusLabel.setText("Semester " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterSubmitButtonActionPerformed

    private void Admin_DisplayClassList_Display_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_DisplayClassList_Display_ButtonActionPerformed
        String courseCode = (String) Admin_DisplayClassList_ChooseClass_ComboBox.getSelectedItem();
        if (courseCode == null) return;

        // Scheduled table model
        javax.swing.table.DefaultTableModel schedModel =
            (javax.swing.table.DefaultTableModel) Admin_DisplayClassList_ScheduledStudents_Table.getModel();
        schedModel.setRowCount(0);

        // Waitlist table model
        javax.swing.table.DefaultTableModel waitModel =
            (javax.swing.table.DefaultTableModel) Admin_DisplayClassList_WaitlistStudents_Table.getModel();
        waitModel.setRowCount(0);

        // Scheduled
        for (ScheduleEntry se : ScheduleQueries.getScheduledStudentsByClass(currentSemester, courseCode)) {
            StudentEntry s = StudentQueries.getStudent(se.getStudentID());
            if (s != null) {
                schedModel.addRow(new Object[] {
                    s.getLastName(), s.getFirstName(), s.getStudentID()
                });
            }
        }

        // Waitlisted (in timestamp order)
        for (ScheduleEntry se : ScheduleQueries.getWaitlistedStudentsByClass(currentSemester, courseCode)) {
            StudentEntry s = StudentQueries.getStudent(se.getStudentID());
            if (s != null) {
                waitModel.addRow(new Object[] {
                    s.getLastName(), s.getFirstName(), s.getStudentID()
                });
            }
        }
    }//GEN-LAST:event_Admin_DisplayClassList_Display_ButtonActionPerformed

    private void Admin_DropStudent_Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_DropStudent_Submit_ButtonActionPerformed
        // TODO add your handling code here:
        StudentEntry toDrop = (StudentEntry) Admin_DropStudent_ChooseStudent_ComboBox.getSelectedItem();
        if (toDrop == null) return;

        String studentID = toDrop.getStudentID();
        String fullName = toDrop.getLastName() + ", " + toDrop.getFirstName() + " " + studentID;

        StringBuilder sb = new StringBuilder();
        sb.append(fullName).append(" has been dropped from the list of students.\n\n");

        // Get all semesters where this student appears in schedule
        ArrayList<String> semesters = ScheduleQueries.getSemestersForStudent(studentID);

        for (String sem : semesters) {
            sb.append("For Semester: ").append(sem).append("\n");

            // All schedule entries for this student in this semester
            ArrayList<ScheduleEntry> entries =
                ScheduleQueries.getScheduleByStudent(sem, studentID);

            for (ScheduleEntry se : entries) {
                String course = se.getCourseCode();

                if (se.getStatus().equals("S")) {
                    // They were scheduled
                    sb.append(fullName).append(" has been dropped from ").append(course).append("\n");

                    // Delete this row
                    ScheduleQueries.deleteScheduleEntry(sem, course, studentID);

                    // Promote first waitlisted student if any
                    ArrayList<ScheduleEntry> waitList =
                        ScheduleQueries.getWaitlistedStudentsByClass(sem, course);
                    if (!waitList.isEmpty()) {
                        ScheduleEntry promoted = waitList.get(0);
                        ScheduleQueries.updateStatus(sem, course, promoted.getStudentID(), "S");

                        StudentEntry promotedStudent =
                            StudentQueries.getStudent(promoted.getStudentID());
                        if (promotedStudent != null) {
                            String promoName = promotedStudent.getLastName() + ", " +
                                               promotedStudent.getFirstName() + " " +
                                               promotedStudent.getStudentID();
                            sb.append(promoName).append(" has been scheduled into ")
                              .append(course).append("\n");
                        }
                    }
                } else { // they were waitlisted
                    sb.append(fullName).append(" has been dropped from the waitlist for ")
                      .append(course).append("\n");
                    ScheduleQueries.deleteScheduleEntry(sem, course, studentID);
                }
            }
            sb.append("\n");
        }

        // Finally, remove from student table
        StudentQueries.deleteStudent(studentID);

        // Refresh combo boxes
        rebuildStudentComboBoxes();

        Admin_DropStudent_TextArea.setText(sb.toString());
    }//GEN-LAST:event_Admin_DropStudent_Submit_ButtonActionPerformed

    private void Admin_DropClass_Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_DropClass_Submit_ButtonActionPerformed
        // TODO add your handling code here:
        String courseCode = (String) Admin_DropClass_ChoseClass_ComboBox.getSelectedItem();
        if (courseCode == null) return;

        StringBuilder sb = new StringBuilder();

        // All scheduled & waitlisted before deleting
        ArrayList<ScheduleEntry> scheduled =
            ScheduleQueries.getScheduledStudentsByClass(currentSemester, courseCode);
        ArrayList<ScheduleEntry> waitlisted =
            ScheduleQueries.getWaitlistedStudentsByClass(currentSemester, courseCode);

        sb.append("Scheduled students dropped from the course:\n");
        for (ScheduleEntry se : scheduled) {
            StudentEntry s = StudentQueries.getStudent(se.getStudentID());
            if (s != null) {
                sb.append(s.getLastName()).append(",").append(s.getFirstName())
                  .append(" ").append(s.getStudentID()).append("\n");
            }
        }
        sb.append("\nWaitlisted students dropped from the course:\n");
        for (ScheduleEntry se : waitlisted) {
            StudentEntry s = StudentQueries.getStudent(se.getStudentID());
            if (s != null) {
                sb.append(s.getLastName()).append(",").append(s.getFirstName())
                  .append(" ").append(s.getStudentID()).append("\n");
            }
        }

        // Delete schedule rows and class row
        ScheduleQueries.deleteScheduleByClass(currentSemester, courseCode);
        ClassQueries.dropClass(currentSemester, courseCode);

        // Refresh all class-related combos
        rebuildClassComboBoxes();

        Admin_DropClass_TextArea.setText(sb.toString());
    }//GEN-LAST:event_Admin_DropClass_Submit_ButtonActionPerformed

    private void Student_DropClass_Submit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_DropClass_Submit_ButtonActionPerformed
        // TODO add your handling code here:
        StudentEntry student = (StudentEntry) Student_DropClass_ChooseStudent_ComboBox.getSelectedItem();
        String courseCode = (String) Student_DropClass_ChooseClass_ComboBox.getSelectedItem();

        if (student == null || courseCode == null) {
            Student_DropClass_TextArea.setText("Please choose both student and class.");
            return;
        }

        String studentID = student.getStudentID();
        String name = student.getLastName() + ", " + student.getFirstName() + " " + studentID;

        // Find their schedule entry (S or W) for this class
        ArrayList<ScheduleEntry> entries =
            ScheduleQueries.getScheduleByStudent(currentSemester, studentID);

        ScheduleEntry target = null;
        for (ScheduleEntry se : entries) {
            if (se.getCourseCode().equals(courseCode)) {
                target = se;
                break;
            }
        }

        if (target == null) {
            Student_DropClass_TextArea.setText("Student is not in that class this semester.");
            return;
        }

        StringBuilder sb = new StringBuilder();

        // If they were scheduled – promote first waitlist
        if (target.getStatus().equals("S")) {
            ScheduleQueries.deleteScheduleEntry(currentSemester, courseCode, studentID);
            sb.append(name).append(" has been dropped from ").append(courseCode).append("\n");

            ArrayList<ScheduleEntry> waitList =
                ScheduleQueries.getWaitlistedStudentsByClass(currentSemester, courseCode);
            if (!waitList.isEmpty()) {
                ScheduleEntry promoted = waitList.get(0);
                ScheduleQueries.updateStatus(currentSemester, courseCode, promoted.getStudentID(), "S");

                StudentEntry promotedStudent = StudentQueries.getStudent(promoted.getStudentID());
                if (promotedStudent != null) {
                    String promoName = promotedStudent.getLastName() + ", " +
                                       promotedStudent.getFirstName() + " " +
                                       promotedStudent.getStudentID();
                    sb.append(promoName).append(" has been scheduled into ")
                      .append(courseCode).append("\n");
                }
            }
        } else { // they were waitlisted
            ScheduleQueries.deleteScheduleEntry(currentSemester, courseCode, studentID);
            sb.append(name).append(" has been dropped from ").append(courseCode)
              .append(" waitlist\n");
        }

        Student_DropClass_TextArea.setText(sb.toString());
    }//GEN-LAST:event_Student_DropClass_Submit_ButtonActionPerformed

    private void Student_DropClass_ChooseStudent_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Student_DropClass_ChooseStudent_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Student_DropClass_ChooseStudent_ComboBoxActionPerformed

    
    private void checkData() {
        try {
            FileReader reader = new FileReader("xzq789yy.txt");
            BufferedReader breader = new BufferedReader(reader);

            String encodedAuthor = breader.readLine();
            String encodedProject = breader.readLine();
            byte[] decodedAuthor = Base64.getDecoder().decode(encodedAuthor);
            author = new String(decodedAuthor);
            byte[] decodedProject = Base64.getDecoder().decode(encodedProject);
            projectDate = new String(decodedProject);
            reader.close();

        } catch (FileNotFoundException e) {
            //get user info and create file
            author = JOptionPane.showInputDialog("Enter your first and last name.");
            projectDate = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime()).toString();

            //write data to the data file.
            try {
                FileWriter writer = new FileWriter("xzq789yy.txt", true);
                BufferedWriter bufferedWriter = new BufferedWriter(writer);

                // encode the output data.
                String encodedAuthor = Base64.getEncoder().encodeToString(author.getBytes());

                bufferedWriter.write(encodedAuthor);
                bufferedWriter.newLine();

                String encodedProject = Base64.getEncoder().encodeToString(projectDate.getBytes());
                bufferedWriter.write(encodedProject);

                bufferedWriter.close();
            } catch (IOException ioe) {
                ioe.printStackTrace();
                System.exit(1);
            }

        } catch (IOException e) {
            e.printStackTrace();
            System.exit(1);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AddClass_CourseCode_ComboBox;
    private javax.swing.JLabel AddClass_Display_textfield;
    private javax.swing.JSpinner AddClass_Seats_Spinner;
    private javax.swing.JButton AddClass_submit_Button;
    private javax.swing.JLabel AddStudent_Display_TextField;
    private javax.swing.JTextField AddStudent_FirstName_TextField;
    private javax.swing.JTextField AddStudent_LastName_TextField;
    private javax.swing.JComboBox<String> Admin_DisplayClassList_ChooseClass_ComboBox;
    private javax.swing.JLabel Admin_DisplayClassList_ChooseClass_Label;
    private javax.swing.JButton Admin_DisplayClassList_Display_Button;
    private javax.swing.JLabel Admin_DisplayClassList_ScheduledStudents_Label;
    private javax.swing.JTable Admin_DisplayClassList_ScheduledStudents_Table;
    private javax.swing.JLabel Admin_DisplayClassList_WaitlistStudents_Label;
    private javax.swing.JTable Admin_DisplayClassList_WaitlistStudents_Table;
    private javax.swing.JComboBox<String> Admin_DropClass_ChoseClass_ComboBox;
    private javax.swing.JLabel Admin_DropClass_ChoseClass_Label;
    private javax.swing.JButton Admin_DropClass_Submit_Button;
    private javax.swing.JTextArea Admin_DropClass_TextArea;
    private javax.swing.JComboBox<String> Admin_DropStudent_ChooseStudent_ComboBox;
    private javax.swing.JLabel Admin_DropStudent_ChooseStudent_Label;
    private javax.swing.JButton Admin_DropStudent_Submit_Button;
    private javax.swing.JTextArea Admin_DropStudent_TextArea;
    private javax.swing.JTabbedPane Admin_Panel;
    private javax.swing.JButton DisplayClasses_Display_Button;
    private javax.swing.JTextArea DisplayClasses_TextArea;
    private javax.swing.JButton DisplaySchedule_Display_Button;
    private javax.swing.JComboBox<String> DisplaySchedule_SelectStudent_ComboBox;
    private javax.swing.JTable DisplaySchedule_Table;
    private javax.swing.JTextArea DisplaySchedule_TextArea;
    private javax.swing.JLabel ScheduleClass_DisplayClassStudent_Label;
    private javax.swing.JComboBox<String> ScheduleClass_SelectClass_ComboBox;
    private javax.swing.JComboBox<String> ScheduleClass_SelectStudent_ComboBox;
    private javax.swing.JButton ScheduleClass_Submit_Button;
    private javax.swing.JTextField StudentIDtextfield;
    private javax.swing.JComboBox<String> Student_DropClass_ChooseClass_ComboBox;
    private javax.swing.JLabel Student_DropClass_ChooseClass_Label;
    private javax.swing.JComboBox<String> Student_DropClass_ChooseStudent_ComboBox;
    private javax.swing.JLabel Student_DropClass_ChooseStudent_Label;
    private javax.swing.JButton Student_DropClass_Submit_Button;
    private javax.swing.JTextArea Student_DropClass_TextArea;
    private javax.swing.JButton aboutButton;
    private javax.swing.JTextField addCourseCodeTextfield;
    private javax.swing.JTextField addCourseDescriptionTextfield;
    private javax.swing.JLabel addCourseStatusLabel;
    private javax.swing.JButton addCourseSubmitButton;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTermTextfield;
    private javax.swing.JTextField addSemesterYearTextfield;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
